const apiUrl = {
  BASEURL: "http://localhost:8081/api",
  IMAGEURL: "http://localhost:8081",
  GET_WEB_BANNER: "/banner/getwebbanner",
  GET_APP_BANNER: "/banner/getappbanner",
  CREATE_BANNERS: "/banner/createbanner",
  EDIT_BANNERS: "/banner/updatebanner/",
  DELETE_BANNERS: "/banner/deletebanner/",
  CREATE_COURSE: "/mycourse/addcourse",
  GET_All_COURSE: "/mycourse/getallcourses",
  ADD_MODULES: "/coursemodule/addmodules",
  GET_MODULES_BY_ID: "/coursemodule/getmodulesbyid/",
  GET_ALL_MODULES: "/coursemodule/getallmodules",
  ADD_VIDEO_MODULES: "/video-module/addvideoformodule",
  GET_ALL_VIDEO: "/video-module/getallvideos",
  GET_VIDEO_BY_MODULE_ID: "/video-module/getvideobymoduleid/",
  ADD_DOCUMENT_MODULES: "/document-module/adddocumentformodule",
  GET_ALL_BY_DOCUMENT: "/document-module/getdocumentbymoduleid",
  GET_ALL_DOCUMENT: "/document-module/getalldocuments",
  ADD_IMAGE_MODULES: "/image-module/addimageformodule",
  GET_ALL_IMAGE: "/image-module/getallimages",
  ADD_ZIP_MODULES: "/zip-module/addzipformodule",
  GET_ALL_ZIP: "/zip-module/getallzip",
  ADD_COUPON: "/coupon/addcoupon",
  GET_ALL_COUPON: "/coupon/getallcoupon",
  DELETE_COUPON: "/coupon/deletecoupon/",
  ACTIVE_COUPON: "/coupon/makecouponactive/",
  INACTIVE_COUPON: "/coupon/makecouponinactive/",
  APPLY_COUPON_FOR_COURSE: "/coupon/applycouponforcourse/",
  ADD_FREEMATERIAL_DOCUMENT: "/freematerial/adddocuments",
  GET_FREEMATERIAL_DOCUMENT: "/freematerial/getalldocument",
  DELETE_FREEMATERIAL_DOCUMENT: "/freematerial/deletedocuments/",
  DELETE_FREEMATERIAL_VIDEO: "/freematerial/deletevideo/",
  ADD_FREEMATERIAL_VIDEO: "/freematerial/addlink",
  GET_FREEMATERIAL_VIDEO: "/freematerial/getallvideo",
};

export { apiUrl };
